### PR TITLE
Adding Passive event listener options

### PR DESCRIPTION
**Pull request by EmilsM**
Setting Passive Event Listener options to false, because Chrome, in the newest versions, sets events as Passive. This means, that e.preventDefault() cannot be used and that throws an error in the console, and, when scrolling the container, scrolls the entire page.

### CODE REVIEW

**Comment by mercs600** [comment]
thanks @EmilsM  good point, but please notice that this library just importing the original perfect-scrollbar lib and this PR should be report there. What's more I see they are working on it: https://github.com/mdbootstrap/perfect-scrollbar/pull/945 - so when they merge this PR I will upgrade this library.

**Comment by andrei-gheorghiu** [comment]
@EmilsM , simply replacing `false` with `{passive: false}` won't cut it (on browsers without support for object syntax it will revert the intended value, as `{passive: false}` is truthy). So you need feature detection.

When (and if) my PR gets merged into `perfect-scrollbar`, `vue2-perfect-scrollbar` will also get the fix.

**Comment by hmoffatt** [comment]
According to https://caniuse.com/mdn-api_eventtarget_addeventlistener_options support for the options/boolean is pretty widespread @andrei-gheorghiu - do you think the feature detection is important?

**Comment by andrei-gheorghiu** [comment]
@hmoffatt yes, I do. It's about supporting legacy browsers. There are two aspects to consider here:

 a) the importance of supporting legacy browsers varies from client to client. Although, a client with outrageous requirements from this POV (e.g: an energy supplier, national bank, post office) will never use this library anyways, specifically because they want to support very old browsers to serve every single request, even if made in ancient browsers.
 
 b) the other important aspect here is that, in legacy browsers, passing the new syntax (`{ passive: true | false }`) instead of the old syntax: `true | false`, actually means `true`, because an object is always truthy. For this particular library, that is a problem. Passing `passive` always `true` means it won't be able to call `preventDefault` on scroll, which means it won't work. As in: _"in legacy browsers it will completely stop working, although it used to work until now"_. 
 
 So yeah, I'd say feature detection is sort of important on this one.

**Pull request closed without merging**
