### PR TITLE
WIP feat/vue3

### PR DESCRIPTION
**Pull request by crutch12**
solves: https://github.com/mercs600/vue2-perfect-scrollbar/issues/60

TODO:
- fix tests (they don't work, I don't know why)

@mercs600 I think we should create @next version (and npm tag) for vue3 contributions.

### CODE REVIEW

**Comment by mercs600** [comment]
Nice work @crutch12 I will merge it and add new tests config, because new Vue test utils can work with jest only.

**Comment by crutch12** [comment]
@mercs600 could you create npm @next tag or update lib major version (2.0.0)?

**Comment by mercs600** [comment]
@crutch12 I would like to avoid naming issues, so I created separate package https://github.com/mercs600/vue3-perfect-scrollbar

**Comment by crutch12** [comment]
@mercs600 great!

**Pull request merged**
